/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as DevRouteImport } from './routes/dev'
import { Route as Dev3RouteImport } from './routes/dev3'
import { Route as ElenaCoachRouteImport } from './routes/elena-coach'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ApiClaudeMessageRouteImport } from './routes/api/claude-message'
import { Route as ApiElenaAgentRouteImport } from './routes/api/elena-agent'
import { Route as ApiElenaCancelRouteImport } from './routes/api/elena-cancel'
import { Route as ApiElenaChatRouteImport } from './routes/api/elena-chat'
import { Route as ApiElenaChatV2RouteImport } from './routes/api/elena-chat-v2'
import { Route as ApiElenaE2bRouteImport } from './routes/api/elena-e2b'
import { Route as ApiElenaQaVisualPixelRouteImport } from './routes/api/elena-qa-visual-pixel'
import { Route as ApiElenaSummarizeRouteImport } from './routes/api/elena-summarize'
import { Route as ApiElenaWorkspaceRouteImport } from './routes/api/elena-workspace'
import { Route as ApiEmbedDocRouteImport } from './routes/api/embed-doc'
import { Route as ApiHeygenSessionRouteImport } from './routes/api/heygen-session'
import { Route as ApiImportProjectRouteImport } from './routes/api/import-project'
import { Route as ApiLiveblocksAuthRouteImport } from './routes/api/liveblocks-auth'
import { Route as ApiPilotSuggestRouteImport } from './routes/api/pilot-suggest'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime-session'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiSeedMemoryRouteImport } from './routes/api/seed-memory'
import { Route as ApiTestProviderKeyRouteImport } from './routes/api/test-provider-key'
import { Route as ApiVideoGenerateRouteImport } from './routes/api/video-generate'
import { Route as ApiPublicAutoSnapshotRouteImport } from './routes/api/public/auto-snapshot'
import { Route as ApiIntegrationsOauthCallbackRouteImport } from './routes/api/integrations/oauth/callback'
import { Route as ApiIntegrationsOauthStartRouteImport } from './routes/api/integrations/oauth/start'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const Dev3Route = Dev3RouteImport.update({
  id: '/dev3',
  path: '/dev3',
  getParentRoute: () => rootRouteImport,
} as any)
const ElenaCoachRoute = ElenaCoachRouteImport.update({
  id: '/elena-coach',
  path: '/elena-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeMessageRoute = ApiClaudeMessageRouteImport.update({
  id: '/api/claude-message',
  path: '/api/claude-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaAgentRoute = ApiElenaAgentRouteImport.update({
  id: '/api/elena-agent',
  path: '/api/elena-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaCancelRoute = ApiElenaCancelRouteImport.update({
  id: '/api/elena-cancel',
  path: '/api/elena-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaChatRoute = ApiElenaChatRouteImport.update({
  id: '/api/elena-chat',
  path: '/api/elena-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaChatV2Route = ApiElenaChatV2RouteImport.update({
  id: '/api/elena-chat-v2',
  path: '/api/elena-chat-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaE2bRoute = ApiElenaE2bRouteImport.update({
  id: '/api/elena-e2b',
  path: '/api/elena-e2b',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaQaVisualPixelRoute = ApiElenaQaVisualPixelRouteImport.update({
  id: '/api/elena-qa-visual-pixel',
  path: '/api/elena-qa-visual-pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaSummarizeRoute = ApiElenaSummarizeRouteImport.update({
  id: '/api/elena-summarize',
  path: '/api/elena-summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElenaWorkspaceRoute = ApiElenaWorkspaceRouteImport.update({
  id: '/api/elena-workspace',
  path: '/api/elena-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedDocRoute = ApiEmbedDocRouteImport.update({
  id: '/api/embed-doc',
  path: '/api/embed-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeygenSessionRoute = ApiHeygenSessionRouteImport.update({
  id: '/api/heygen-session',
  path: '/api/heygen-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportProjectRoute = ApiImportProjectRouteImport.update({
  id: '/api/import-project',
  path: '/api/import-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveblocksAuthRoute = ApiLiveblocksAuthRouteImport.update({
  id: '/api/liveblocks-auth',
  path: '/api/liveblocks-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPilotSuggestRoute = ApiPilotSuggestRouteImport.update({
  id: '/api/pilot-suggest',
  path: '/api/pilot-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime-session',
  path: '/api/realtime-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedMemoryRoute = ApiSeedMemoryRouteImport.update({
  id: '/api/seed-memory',
  path: '/api/seed-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestProviderKeyRoute = ApiTestProviderKeyRouteImport.update({
  id: '/api/test-provider-key',
  path: '/api/test-provider-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenerateRoute = ApiVideoGenerateRouteImport.update({
  id: '/api/video-generate',
  path: '/api/video-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutoSnapshotRoute = ApiPublicAutoSnapshotRouteImport.update({
  id: '/api/public/auto-snapshot',
  path: '/api/public/auto-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsOauthCallbackRoute =
  ApiIntegrationsOauthCallbackRouteImport.update({
    id: '/api/integrations/oauth/callback',
    path: '/api/integrations/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsOauthStartRoute =
  ApiIntegrationsOauthStartRouteImport.update({
    id: '/api/integrations/oauth/start',
    path: '/api/integrations/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/comparison': typeof ComparisonRoute
  '/dev': typeof DevRoute
  '/dev3': typeof Dev3Route
  '/elena-coach': typeof ElenaCoachRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/thank-you': typeof ThankYouRoute
  '/trust': typeof TrustRoute
  '/api/claude-message': typeof ApiClaudeMessageRoute
  '/api/elena-agent': typeof ApiElenaAgentRoute
  '/api/elena-cancel': typeof ApiElenaCancelRoute
  '/api/elena-chat': typeof ApiElenaChatRoute
  '/api/elena-chat-v2': typeof ApiElenaChatV2Route
  '/api/elena-e2b': typeof ApiElenaE2bRoute
  '/api/elena-qa-visual-pixel': typeof ApiElenaQaVisualPixelRoute
  '/api/elena-summarize': typeof ApiElenaSummarizeRoute
  '/api/elena-workspace': typeof ApiElenaWorkspaceRoute
  '/api/embed-doc': typeof ApiEmbedDocRoute
  '/api/heygen-session': typeof ApiHeygenSessionRoute
  '/api/import-project': typeof ApiImportProjectRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/pilot-suggest': typeof ApiPilotSuggestRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/seed-memory': typeof ApiSeedMemoryRoute
  '/api/test-provider-key': typeof ApiTestProviderKeyRoute
  '/api/video-generate': typeof ApiVideoGenerateRoute
  '/api/public/auto-snapshot': typeof ApiPublicAutoSnapshotRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
  '/api/integrations/oauth/start': typeof ApiIntegrationsOauthStartRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/comparison': typeof ComparisonRoute
  '/dev': typeof DevRoute
  '/dev3': typeof Dev3Route
  '/elena-coach': typeof ElenaCoachRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/thank-you': typeof ThankYouRoute
  '/trust': typeof TrustRoute
  '/api/claude-message': typeof ApiClaudeMessageRoute
  '/api/elena-agent': typeof ApiElenaAgentRoute
  '/api/elena-cancel': typeof ApiElenaCancelRoute
  '/api/elena-chat': typeof ApiElenaChatRoute
  '/api/elena-chat-v2': typeof ApiElenaChatV2Route
  '/api/elena-e2b': typeof ApiElenaE2bRoute
  '/api/elena-qa-visual-pixel': typeof ApiElenaQaVisualPixelRoute
  '/api/elena-summarize': typeof ApiElenaSummarizeRoute
  '/api/elena-workspace': typeof ApiElenaWorkspaceRoute
  '/api/embed-doc': typeof ApiEmbedDocRoute
  '/api/heygen-session': typeof ApiHeygenSessionRoute
  '/api/import-project': typeof ApiImportProjectRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/pilot-suggest': typeof ApiPilotSuggestRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/seed-memory': typeof ApiSeedMemoryRoute
  '/api/test-provider-key': typeof ApiTestProviderKeyRoute
  '/api/video-generate': typeof ApiVideoGenerateRoute
  '/api/public/auto-snapshot': typeof ApiPublicAutoSnapshotRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
  '/api/integrations/oauth/start': typeof ApiIntegrationsOauthStartRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/comparison': typeof ComparisonRoute
  '/dev': typeof DevRoute
  '/dev3': typeof Dev3Route
  '/elena-coach': typeof ElenaCoachRoute
  '/feedback': typeof FeedbackRoute
  '/integrations': typeof IntegrationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/thank-you': typeof ThankYouRoute
  '/trust': typeof TrustRoute
  '/api/claude-message': typeof ApiClaudeMessageRoute
  '/api/elena-agent': typeof ApiElenaAgentRoute
  '/api/elena-cancel': typeof ApiElenaCancelRoute
  '/api/elena-chat': typeof ApiElenaChatRoute
  '/api/elena-chat-v2': typeof ApiElenaChatV2Route
  '/api/elena-e2b': typeof ApiElenaE2bRoute
  '/api/elena-qa-visual-pixel': typeof ApiElenaQaVisualPixelRoute
  '/api/elena-summarize': typeof ApiElenaSummarizeRoute
  '/api/elena-workspace': typeof ApiElenaWorkspaceRoute
  '/api/embed-doc': typeof ApiEmbedDocRoute
  '/api/heygen-session': typeof ApiHeygenSessionRoute
  '/api/import-project': typeof ApiImportProjectRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/api/pilot-suggest': typeof ApiPilotSuggestRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/seed-memory': typeof ApiSeedMemoryRoute
  '/api/test-provider-key': typeof ApiTestProviderKeyRoute
  '/api/video-generate': typeof ApiVideoGenerateRoute
  '/api/public/auto-snapshot': typeof ApiPublicAutoSnapshotRoute
  '/api/integrations/oauth/callback': typeof ApiIntegrationsOauthCallbackRoute
  '/api/integrations/oauth/start': typeof ApiIntegrationsOauthStartRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/capabilities'
    | '/chat'
    | '/comparison'
    | '/dev'
    | '/dev3'
    | '/elena-coach'
    | '/feedback'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/showcase'
    | '/thank-you'
    | '/trust'
    | '/api/claude-message'
    | '/api/elena-agent'
    | '/api/elena-cancel'
    | '/api/elena-chat'
    | '/api/elena-chat-v2'
    | '/api/elena-e2b'
    | '/api/elena-qa-visual-pixel'
    | '/api/elena-summarize'
    | '/api/elena-workspace'
    | '/api/embed-doc'
    | '/api/heygen-session'
    | '/api/import-project'
    | '/api/liveblocks-auth'
    | '/api/pilot-suggest'
    | '/api/realtime-session'
    | '/api/scrape'
    | '/api/seed-memory'
    | '/api/test-provider-key'
    | '/api/video-generate'
    | '/api/public/auto-snapshot'
    | '/api/integrations/oauth/callback'
    | '/api/integrations/oauth/start'
    | '/api/public/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/capabilities'
    | '/chat'
    | '/comparison'
    | '/dev'
    | '/dev3'
    | '/elena-coach'
    | '/feedback'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/showcase'
    | '/thank-you'
    | '/trust'
    | '/api/claude-message'
    | '/api/elena-agent'
    | '/api/elena-cancel'
    | '/api/elena-chat'
    | '/api/elena-chat-v2'
    | '/api/elena-e2b'
    | '/api/elena-qa-visual-pixel'
    | '/api/elena-summarize'
    | '/api/elena-workspace'
    | '/api/embed-doc'
    | '/api/heygen-session'
    | '/api/import-project'
    | '/api/liveblocks-auth'
    | '/api/pilot-suggest'
    | '/api/realtime-session'
    | '/api/scrape'
    | '/api/seed-memory'
    | '/api/test-provider-key'
    | '/api/video-generate'
    | '/api/public/auto-snapshot'
    | '/api/integrations/oauth/callback'
    | '/api/integrations/oauth/start'
    | '/api/public/github/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/capabilities'
    | '/chat'
    | '/comparison'
    | '/dev'
    | '/dev3'
    | '/elena-coach'
    | '/feedback'
    | '/integrations'
    | '/projects'
    | '/settings'
    | '/showcase'
    | '/thank-you'
    | '/trust'
    | '/api/claude-message'
    | '/api/elena-agent'
    | '/api/elena-cancel'
    | '/api/elena-chat'
    | '/api/elena-chat-v2'
    | '/api/elena-e2b'
    | '/api/elena-qa-visual-pixel'
    | '/api/elena-summarize'
    | '/api/elena-workspace'
    | '/api/embed-doc'
    | '/api/heygen-session'
    | '/api/import-project'
    | '/api/liveblocks-auth'
    | '/api/pilot-suggest'
    | '/api/realtime-session'
    | '/api/scrape'
    | '/api/seed-memory'
    | '/api/test-provider-key'
    | '/api/video-generate'
    | '/api/public/auto-snapshot'
    | '/api/integrations/oauth/callback'
    | '/api/integrations/oauth/start'
    | '/api/public/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ChatRoute: typeof ChatRoute
  ComparisonRoute: typeof ComparisonRoute
  DevRoute: typeof DevRoute
  Dev3Route: typeof Dev3Route
  ElenaCoachRoute: typeof ElenaCoachRoute
  FeedbackRoute: typeof FeedbackRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  ShowcaseRoute: typeof ShowcaseRoute
  ThankYouRoute: typeof ThankYouRoute
  TrustRoute: typeof TrustRoute
  ApiClaudeMessageRoute: typeof ApiClaudeMessageRoute
  ApiElenaAgentRoute: typeof ApiElenaAgentRoute
  ApiElenaCancelRoute: typeof ApiElenaCancelRoute
  ApiElenaChatRoute: typeof ApiElenaChatRoute
  ApiElenaChatV2Route: typeof ApiElenaChatV2Route
  ApiElenaE2bRoute: typeof ApiElenaE2bRoute
  ApiElenaQaVisualPixelRoute: typeof ApiElenaQaVisualPixelRoute
  ApiElenaSummarizeRoute: typeof ApiElenaSummarizeRoute
  ApiElenaWorkspaceRoute: typeof ApiElenaWorkspaceRoute
  ApiEmbedDocRoute: typeof ApiEmbedDocRoute
  ApiHeygenSessionRoute: typeof ApiHeygenSessionRoute
  ApiImportProjectRoute: typeof ApiImportProjectRoute
  ApiLiveblocksAuthRoute: typeof ApiLiveblocksAuthRoute
  ApiPilotSuggestRoute: typeof ApiPilotSuggestRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  ApiSeedMemoryRoute: typeof ApiSeedMemoryRoute
  ApiTestProviderKeyRoute: typeof ApiTestProviderKeyRoute
  ApiVideoGenerateRoute: typeof ApiVideoGenerateRoute
  ApiPublicAutoSnapshotRoute: typeof ApiPublicAutoSnapshotRoute
  ApiIntegrationsOauthCallbackRoute: typeof ApiIntegrationsOauthCallbackRoute
  ApiIntegrationsOauthStartRoute: typeof ApiIntegrationsOauthStartRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev3': {
      id: '/dev3'
      path: '/dev3'
      fullPath: '/dev3'
      preLoaderRoute: typeof Dev3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elena-coach': {
      id: '/elena-coach'
      path: '/elena-coach'
      fullPath: '/elena-coach'
      preLoaderRoute: typeof ElenaCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude-message': {
      id: '/api/claude-message'
      path: '/api/claude-message'
      fullPath: '/api/claude-message'
      preLoaderRoute: typeof ApiClaudeMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-agent': {
      id: '/api/elena-agent'
      path: '/api/elena-agent'
      fullPath: '/api/elena-agent'
      preLoaderRoute: typeof ApiElenaAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-cancel': {
      id: '/api/elena-cancel'
      path: '/api/elena-cancel'
      fullPath: '/api/elena-cancel'
      preLoaderRoute: typeof ApiElenaCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-chat': {
      id: '/api/elena-chat'
      path: '/api/elena-chat'
      fullPath: '/api/elena-chat'
      preLoaderRoute: typeof ApiElenaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-chat-v2': {
      id: '/api/elena-chat-v2'
      path: '/api/elena-chat-v2'
      fullPath: '/api/elena-chat-v2'
      preLoaderRoute: typeof ApiElenaChatV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-e2b': {
      id: '/api/elena-e2b'
      path: '/api/elena-e2b'
      fullPath: '/api/elena-e2b'
      preLoaderRoute: typeof ApiElenaE2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-qa-visual-pixel': {
      id: '/api/elena-qa-visual-pixel'
      path: '/api/elena-qa-visual-pixel'
      fullPath: '/api/elena-qa-visual-pixel'
      preLoaderRoute: typeof ApiElenaQaVisualPixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-summarize': {
      id: '/api/elena-summarize'
      path: '/api/elena-summarize'
      fullPath: '/api/elena-summarize'
      preLoaderRoute: typeof ApiElenaSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elena-workspace': {
      id: '/api/elena-workspace'
      path: '/api/elena-workspace'
      fullPath: '/api/elena-workspace'
      preLoaderRoute: typeof ApiElenaWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed-doc': {
      id: '/api/embed-doc'
      path: '/api/embed-doc'
      fullPath: '/api/embed-doc'
      preLoaderRoute: typeof ApiEmbedDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heygen-session': {
      id: '/api/heygen-session'
      path: '/api/heygen-session'
      fullPath: '/api/heygen-session'
      preLoaderRoute: typeof ApiHeygenSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-project': {
      id: '/api/import-project'
      path: '/api/import-project'
      fullPath: '/api/import-project'
      preLoaderRoute: typeof ApiImportProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liveblocks-auth': {
      id: '/api/liveblocks-auth'
      path: '/api/liveblocks-auth'
      fullPath: '/api/liveblocks-auth'
      preLoaderRoute: typeof ApiLiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pilot-suggest': {
      id: '/api/pilot-suggest'
      path: '/api/pilot-suggest'
      fullPath: '/api/pilot-suggest'
      preLoaderRoute: typeof ApiPilotSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-session': {
      id: '/api/realtime-session'
      path: '/api/realtime-session'
      fullPath: '/api/realtime-session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-memory': {
      id: '/api/seed-memory'
      path: '/api/seed-memory'
      fullPath: '/api/seed-memory'
      preLoaderRoute: typeof ApiSeedMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-provider-key': {
      id: '/api/test-provider-key'
      path: '/api/test-provider-key'
      fullPath: '/api/test-provider-key'
      preLoaderRoute: typeof ApiTestProviderKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-generate': {
      id: '/api/video-generate'
      path: '/api/video-generate'
      fullPath: '/api/video-generate'
      preLoaderRoute: typeof ApiVideoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auto-snapshot': {
      id: '/api/public/auto-snapshot'
      path: '/api/public/auto-snapshot'
      fullPath: '/api/public/auto-snapshot'
      preLoaderRoute: typeof ApiPublicAutoSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/oauth/callback': {
      id: '/api/integrations/oauth/callback'
      path: '/api/integrations/oauth/callback'
      fullPath: '/api/integrations/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/oauth/start': {
      id: '/api/integrations/oauth/start'
      path: '/api/integrations/oauth/start'
      fullPath: '/api/integrations/oauth/start'
      preLoaderRoute: typeof ApiIntegrationsOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ChatRoute: ChatRoute,
  ComparisonRoute: ComparisonRoute,
  DevRoute: DevRoute,
  Dev3Route: Dev3Route,
  ElenaCoachRoute: ElenaCoachRoute,
  FeedbackRoute: FeedbackRoute,
  IntegrationsRoute: IntegrationsRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  ShowcaseRoute: ShowcaseRoute,
  ThankYouRoute: ThankYouRoute,
  TrustRoute: TrustRoute,
  ApiClaudeMessageRoute: ApiClaudeMessageRoute,
  ApiElenaAgentRoute: ApiElenaAgentRoute,
  ApiElenaCancelRoute: ApiElenaCancelRoute,
  ApiElenaChatRoute: ApiElenaChatRoute,
  ApiElenaChatV2Route: ApiElenaChatV2Route,
  ApiElenaE2bRoute: ApiElenaE2bRoute,
  ApiElenaQaVisualPixelRoute: ApiElenaQaVisualPixelRoute,
  ApiElenaSummarizeRoute: ApiElenaSummarizeRoute,
  ApiElenaWorkspaceRoute: ApiElenaWorkspaceRoute,
  ApiEmbedDocRoute: ApiEmbedDocRoute,
  ApiHeygenSessionRoute: ApiHeygenSessionRoute,
  ApiImportProjectRoute: ApiImportProjectRoute,
  ApiLiveblocksAuthRoute: ApiLiveblocksAuthRoute,
  ApiPilotSuggestRoute: ApiPilotSuggestRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  ApiSeedMemoryRoute: ApiSeedMemoryRoute,
  ApiTestProviderKeyRoute: ApiTestProviderKeyRoute,
  ApiVideoGenerateRoute: ApiVideoGenerateRoute,
  ApiPublicAutoSnapshotRoute: ApiPublicAutoSnapshotRoute,
  ApiIntegrationsOauthCallbackRoute: ApiIntegrationsOauthCallbackRoute,
  ApiIntegrationsOauthStartRoute: ApiIntegrationsOauthStartRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
